# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\MyCode\ColorChangeAction\Config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(490, 583)
        self.lenameConfig = QtWidgets.QLineEdit(Config)
        self.lenameConfig.setGeometry(QtCore.QRect(100, 280, 131, 31))
        self.lenameConfig.setObjectName("lenameConfig")
        self.label = QtWidgets.QLabel(Config)
        self.label.setGeometry(QtCore.QRect(30, 280, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Config)
        self.label_2.setGeometry(QtCore.QRect(310, 280, 151, 31))
        self.label_2.setObjectName("label_2")
        self.dsbfrequencyConfig = QtWidgets.QDoubleSpinBox(Config)
        self.dsbfrequencyConfig.setGeometry(QtCore.QRect(330, 280, 62, 31))
        self.dsbfrequencyConfig.setDecimals(1)
        self.dsbfrequencyConfig.setMinimum(0.5)
        self.dsbfrequencyConfig.setMaximum(9999.0)
        self.dsbfrequencyConfig.setSingleStep(0.5)
        self.dsbfrequencyConfig.setProperty("value", 5.0)
        self.dsbfrequencyConfig.setObjectName("dsbfrequencyConfig")
        self.btnaddPoint = QtWidgets.QPushButton(Config)
        self.btnaddPoint.setGeometry(QtCore.QRect(360, 320, 91, 31))
        self.btnaddPoint.setObjectName("btnaddPoint")
        self.btnsave = QtWidgets.QPushButton(Config)
        self.btnsave.setGeometry(QtCore.QRect(100, 530, 91, 31))
        self.btnsave.setObjectName("btnsave")
        self.btnexit = QtWidgets.QPushButton(Config)
        self.btnexit.setGeometry(QtCore.QRect(280, 530, 91, 31))
        self.btnexit.setObjectName("btnexit")
        self.label_3 = QtWidgets.QLabel(Config)
        self.label_3.setGeometry(QtCore.QRect(30, 360, 391, 161))
        self.label_3.setObjectName("label_3")
        self.twpoint = QtWidgets.QTableWidget(Config)
        self.twpoint.setGeometry(QtCore.QRect(30, 80, 431, 192))
        self.twpoint.setObjectName("twpoint")
        self.twpoint.setColumnCount(0)
        self.twpoint.setRowCount(0)
        self.twpoint.horizontalHeader().setDefaultSectionSize(60)
        self.btnDeleteRow = QtWidgets.QPushButton(Config)
        self.btnDeleteRow.setGeometry(QtCore.QRect(30, 320, 91, 31))
        self.btnDeleteRow.setObjectName("btnDeleteRow")
        self.cbWindowList = QtWidgets.QComboBox(Config)
        self.cbWindowList.setGeometry(QtCore.QRect(30, 10, 321, 31))
        self.cbWindowList.setObjectName("cbWindowList")
        self.btnRefresh = QtWidgets.QPushButton(Config)
        self.btnRefresh.setGeometry(QtCore.QRect(370, 10, 91, 31))
        self.btnRefresh.setObjectName("btnRefresh")
        self.labelHwnd = QtWidgets.QLabel(Config)
        self.labelHwnd.setGeometry(QtCore.QRect(30, 50, 431, 20))
        self.labelHwnd.setObjectName("labelHwnd")
        self.cbShow = QtWidgets.QComboBox(Config)
        self.cbShow.setGeometry(QtCore.QRect(240, 320, 91, 31))
        self.cbShow.setObjectName("cbShow")

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "方案设置"))
        self.label.setText(_translate("Config", "方案名称:"))
        self.label_2.setText(_translate("Config", "每             秒检测1次"))
        self.btnaddPoint.setText(_translate("Config", "添加"))
        self.btnsave.setText(_translate("Config", "保存"))
        self.btnexit.setText(_translate("Config", "取消"))
        self.label_3.setText(_translate("Config", "<html><head/><body><p>点击添加按键数秒后，自动添加鼠标所在位置的坐标和颜色</p><p>如果是浏览器请先全屏或在使用时固定浏览器窗口大小</p><p>消息和消息背景颜色可直接点击表格修改(功能尚未实现)</p><p>自动获得的坐标有时候会错。请仔细检查</p><p>自动添加坐标时，表格中显示的是client坐标，弹出窗口中是screen坐标</p><p>被检测的窗口可以被遮挡，不能最小化。最小化的窗口不能截图</p></body></html>"))
        self.btnDeleteRow.setText(_translate("Config", "删除所选行"))
        self.btnRefresh.setText(_translate("Config", "刷新"))
        self.labelHwnd.setText(_translate("Config", "未绑定窗口"))
