# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\MyCode\ColorChangeAction\ColorChangeAction.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorChangeAction(object):
    def setupUi(self, ColorChangeAction):
        ColorChangeAction.setObjectName("ColorChangeAction")
        ColorChangeAction.resize(431, 471)
        self.btnProjectConfig = QtWidgets.QPushButton(ColorChangeAction)
        self.btnProjectConfig.setGeometry(QtCore.QRect(320, 80, 91, 31))
        self.btnProjectConfig.setObjectName("btnProjectConfig")
        self.cbWindowList = QtWidgets.QComboBox(ColorChangeAction)
        self.cbWindowList.setGeometry(QtCore.QRect(20, 10, 291, 31))
        self.cbWindowList.setObjectName("cbWindowList")
        self.btnRefresh = QtWidgets.QPushButton(ColorChangeAction)
        self.btnRefresh.setGeometry(QtCore.QRect(320, 10, 91, 31))
        self.btnRefresh.setObjectName("btnRefresh")
        self.labelHwnd = QtWidgets.QLabel(ColorChangeAction)
        self.labelHwnd.setGeometry(QtCore.QRect(20, 50, 391, 16))
        self.labelHwnd.setObjectName("labelHwnd")
        self.leProjectName = QtWidgets.QLineEdit(ColorChangeAction)
        self.leProjectName.setGeometry(QtCore.QRect(20, 80, 181, 31))
        self.leProjectName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leProjectName.setReadOnly(True)
        self.leProjectName.setObjectName("leProjectName")
        self.btnOpenProject = QtWidgets.QPushButton(ColorChangeAction)
        self.btnOpenProject.setGeometry(QtCore.QRect(220, 80, 91, 31))
        self.btnOpenProject.setObjectName("btnOpenProject")
        self.label_3 = QtWidgets.QLabel(ColorChangeAction)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(ColorChangeAction)
        self.label.setGeometry(QtCore.QRect(150, 120, 21, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ColorChangeAction)
        self.label_2.setGeometry(QtCore.QRect(260, 120, 61, 21))
        self.label_2.setObjectName("label_2")
        self.dsbFrequency = QtWidgets.QDoubleSpinBox(ColorChangeAction)
        self.dsbFrequency.setGeometry(QtCore.QRect(180, 120, 62, 22))
        self.dsbFrequency.setDecimals(1)
        self.dsbFrequency.setMaximum(9999.0)
        self.dsbFrequency.setSingleStep(0.5)
        self.dsbFrequency.setProperty("value", 5.0)
        self.dsbFrequency.setObjectName("dsbFrequency")
        self.labelPointNum = QtWidgets.QLabel(ColorChangeAction)
        self.labelPointNum.setGeometry(QtCore.QRect(80, 120, 41, 21))
        self.labelPointNum.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPointNum.setObjectName("labelPointNum")
        self.btnStart = QtWidgets.QPushButton(ColorChangeAction)
        self.btnStart.setGeometry(QtCore.QRect(170, 160, 91, 31))
        self.btnStart.setObjectName("btnStart")
        self.textBrowser = QtWidgets.QTextBrowser(ColorChangeAction)
        self.textBrowser.setGeometry(QtCore.QRect(20, 220, 391, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.btnStop = QtWidgets.QPushButton(ColorChangeAction)
        self.btnStop.setGeometry(QtCore.QRect(320, 160, 91, 31))
        self.btnStop.setObjectName("btnStop")
        self.btnClear = QtWidgets.QPushButton(ColorChangeAction)
        self.btnClear.setGeometry(QtCore.QRect(20, 160, 91, 31))
        self.btnClear.setObjectName("btnClear")

        self.retranslateUi(ColorChangeAction)
        QtCore.QMetaObject.connectSlotsByName(ColorChangeAction)

    def retranslateUi(self, ColorChangeAction):
        _translate = QtCore.QCoreApplication.translate
        ColorChangeAction.setWindowTitle(_translate("ColorChangeAction", "ColorChangeAction"))
        self.btnProjectConfig.setText(_translate("ColorChangeAction", "新建 / 修改"))
        self.btnRefresh.setText(_translate("ColorChangeAction", "刷新"))
        self.labelHwnd.setText(_translate("ColorChangeAction", "未绑定窗口"))
        self.leProjectName.setText(_translate("ColorChangeAction", "选择方案"))
        self.btnOpenProject.setText(_translate("ColorChangeAction", "打开方案"))
        self.label_3.setText(_translate("ColorChangeAction", "检测点数:      个"))
        self.label.setText(_translate("ColorChangeAction", "每"))
        self.label_2.setText(_translate("ColorChangeAction", "秒检测1次"))
        self.labelPointNum.setText(_translate("ColorChangeAction", "0"))
        self.btnStart.setText(_translate("ColorChangeAction", "开始"))
        self.btnStop.setText(_translate("ColorChangeAction", "停止"))
        self.btnClear.setText(_translate("ColorChangeAction", "清屏"))
